MoviesHobbyProject/Models/GroupMembers.cs
using System.ComponentModel.DataAnnotations;

namespace MoviesHobbyProject.Models
{
    public class GroupMembers
    {
        [Key]
        public int GroupMembersID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MemberBio { get; set; }
        public string FavMovieReason { get; set; }
        public string FullName
        {
            get
            {
                return FirstName + " " + LastName;
            }
        }
        public string Slug
        {
            get
            {
                if (FullName == null)
                    return "";
                else
                    return FullName.Replace(' ', '-');
            }
        }
    }
}

MoviesHobbyProject/Controllers/GroupMembersController.cs
using Microsoft.AspNetCore.Mvc;
using MoviesHobbyProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;

namespace MoviesHobbyProject.Controllers
{
    public class GroupMembersController : Controller
    {
        private const string UriString = "https://api.themoviedb.org/3/movie/";
        private const string apiKey = "078923f64c5714a90fb9477198305522";
        private MemberMoviesContext _context;

        public GroupMembersController(MemberMoviesContext ctx)
        {
            _context = ctx;
        }
        public IActionResult About(int id)
        {
            var members = _context.Members.ToList();
            var movies = _context.Movies.OrderBy(n => n.MovieName).ToList();
            var favorites = _context.Favorites.Where(r => r.Rating == 5).ToList();
            var model = new HobbyViewModel
            {
                TeamList = members,
                FavoritesCollection = favorites,
                MoviesList = movies,
                MemID = id
            };
            ViewBag.Title = "About Me";
            return View(model);
        }
        public IActionResult FavoriteMovies(int id)
        {
            var favMovies = _context.Favorites.Where(i => i.GroupMembersID == id).ToList();
            var filteredMovies = new List<SavedMovies>();
            List<string> apiValList = new List<string>();
            List<int> favIdList = new List<int>();
            List<MovieApiModel> apiItemList = new List<MovieApiModel>();
            for (int x = 0; x < favMovies.Count; x++)
            {
                favIdList.Insert(x, favMovies[x].MovieFavoritesID);
            }
            for (int x = 0; x < favMovies.Count; x++)
            {
                var tempMovies = _context.Movies.Where(i => i.SavedMoviesID == favMovies[x].SavedMoviesID);
                foreach(SavedMovies t in tempMovies)
                {
                    filteredMovies.Insert(x, t);
                }
            }
            for (int x = 0; x < filteredMovies.Count; x++)
            {
                string apiIdVal = filteredMovies[x].APIReferenceID.ToString();
                apiValList.Insert(x, apiIdVal);
            }
            for (int x = 0; x < apiValList.Count; x++)
            {
                MovieApiModel movie = new MovieApiModel();
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(UriString);
                    var responseTask = client.GetAsync(apiValList[x] + "?api_key=" + apiKey);
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsAsync<MovieApiModel>();
                        readTask.Wait();

                        movie = readTask.Result;
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Server error. Please contact admin.");
                    }
                    apiItemList.Insert(x, movie);
                }
            }
            var model = new HobbyViewModel
            {
                MoviesList = filteredMovies,
                ApiContentList = apiItemList
            };
            ViewBag.Title = "My Movies List";
            return View(model);
        }
    }
}

MoviesHobbyProject/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using MoviesHobbyProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;

namespace MovieHobbiesProject.Controllers
{
    public class MoviesController : Controller
    {
        private const string UriString = "https://api.themoviedb.org/3/movie/";
        private const string apiKey = "078923f64c5714a90fb9477198305522";
        private readonly MemberMoviesContext _context;

        public MoviesController(MemberMoviesContext ctx)
        {
            _context = ctx;
        }
        public IActionResult ViewAll()
        {
            var allMovies = _context.Movies
                .OrderBy(m => m.MovieName).ToList();
            List<string> apiValList = new List<string>();
            List<MovieApiModel> apiItemList = new List<MovieApiModel>();
            for (int x = 0; x < allMovies.Count; x++)
            {
                string apiIdVal = allMovies[x].APIReferenceID.ToString();
                apiValList.Insert(x, apiIdVal);
            }
            for (int x=0; x < apiValList.Count; x++)
            {
                MovieApiModel movie = new MovieApiModel();
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(UriString);
                    var responseTask = client.GetAsync(apiValList[x] + "?api_key=" + apiKey);
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsAsync<MovieApiModel>();
                        readTask.Wait();

                        movie = readTask.Result;
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Server error. Please contact admin.");
                    }
                    apiItemList.Insert(x, movie);
                }

            }
            var model = new HobbyViewModel
            {
                MoviesList = allMovies,
                ApiContentList = apiItemList
            };
            ViewBag.Title = "All Movies";
            return View(model);
        }
        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Title = "Add A New Movie";
            ViewBag.AddID = "0";
            this.LoadViewBag();
            return View();
        }
        [HttpGet]   //Edit Action is currently unused. Add form will need adjusted to use model components to update.
        public IActionResult Edit(int id)
        {
            ViewBag.Title = "Edit the Movie";
            ViewBag.AddID = id;
            this.LoadViewBag();
            MovieViewModel movieModel = new MovieViewModel
            {
                Movie = _context.Movies
                .FirstOrDefault(m => m.SavedMoviesID == id),
                MovID = id
            };
            return View("Add", movieModel);
        }
        [HttpPost]   //"Edit" portion of this method is currently unused. Add form will need adjusted to use model components to update.
        public IActionResult Edit(MovieViewModel selectedMovie)
        {
            MovieFavorites favorite = new MovieFavorites
            {
                Rating = selectedMovie.FavRating,
                GroupMembersID = selectedMovie.MemID,
                SavedMoviesID = selectedMovie.MovID,
                IsMovie = true,
                MovieInfo = selectedMovie.Movie
            };
            if (ModelState.IsValid)
            {
                if(selectedMovie.MovID == 0)
                {
                    _context.Movies.Add(selectedMovie.Movie);
                    _context.Favorites.Add(favorite);
                }
                else
                {
                    _context.Movies.Update(selectedMovie.Movie);
                    _context.Favorites.Update(favorite);
                }
                _context.SaveChanges();
                return RedirectToAction("ViewAll");
            }
            else
            {
                ViewBag.Title = "Add A New Movie";
                ViewBag.AddID = "0";
                this.LoadViewBag();
                return View("Add");
            }
        }
        public ActionResult MovieDetails(int id)
        {
            ViewBag.Title = "Movie Details";
            var selectedMovie = _context.Movies.FirstOrDefault(x => x.SavedMoviesID == id);
            string apiIdVal = selectedMovie.APIReferenceID.ToString();
            MovieApiModel movie = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(UriString);
                var responseTask = client.GetAsync(apiIdVal + "?api_key=" + apiKey);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<MovieApiModel>();
                    readTask.Wait();

                    movie = readTask.Result;
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error. Please contact admin.");
                }
                return View(movie);
            }
        }

        private void LoadViewBag()
        {
            ViewBag.GroupMembers = _context.Members.ToList();
        }
    }
}

MoviesHobbyProject/Views/GroupMembers/About.cshtml
@model HobbyViewModel
<div class="jumbotron">
    <h1 class="text-center h3">@ViewBag.Title</h1>
</div>
<div class="p-5">
    @foreach (GroupMembers m in Model.TeamList.Where(x => x.GroupMembersID == Model.MemID))
    {
        <h2 class="h4">Name: @m.FullName</h2>
        <p class="lead">@m.MemberBio</p>
        <hr color="gray" />
        @foreach (MovieFavorites f in Model.FavoritesCollection.Where(x => x.GroupMembersID == Model.MemID))
        {
            @foreach (SavedMovies l in Model.MoviesList.Where(y => y.SavedMoviesID == f.SavedMoviesID))
            {
                <div class="row">
                    <div class="col-12">
                        <h3 class="h5">My favorite movie is @l.MovieName!</h3>
                    </div>
                    <div class="col-12">
                        <div class="card-deck">
                            <div class="card p-3 mb-3">
                                <p class="lead">
                                    <em>Learn More About My Favorite: </em>
                                    <a class="btn btn-outline-dark ml-2" asp-area="" asp-controller="Movies"
                           asp-action="MovieDetails" asp-route-slug="@l.Slug"
                           asp-route-id="@l.SavedMoviesID">Learn More</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
        <p class="lead"><span style="font-weight:600;">A little about my favorite: </span>@m.FavMovieReason</p>
        
        <hr color="gray" />
        <div class="col-md-6 col-xs-12">
            <div class="card p-3 mb-3" style="background:url('/images/moviePic.jpg'); background-size: cover; background-position: center;">
                <p class="lead">
                    <em>See other movies I like: </em>
                    <a class="btn btn-outline-dark ml-2" asp-area="" asp-controller="GroupMembers"
                   asp-action="FavoriteMovies" asp-route-slug="@m.Slug"
                   asp-route-id="@m.GroupMembersID">See More</a>
                </p>
            </div>
        </div>
    }
</div>

MoviesHobbyProject/Views/GroupMembers/FavoriteMovies.cshtml
@model HobbyViewModel

<div class="jumbotron">
    <h1 class="text-center h3">@ViewBag.Title</h1>
</div>
<div class="container-fluid">
    <div class="row justify-content-between">

        <div class="card-columns">
            @foreach (MovieApiModel a in Model.ApiContentList)
            {
                <div class="card">
                    <img class="card-img-top" src="https://www.themoviedb.org/t/p/w533_and_h300_bestv2/@a.Backdrop_path" alt="">
                    <div class="card-body">
                        <h2 class="h5 card-title">@a.Title</h2>
                        <p class="card-text lead">@a.Tagline</p>
                        @foreach (SavedMovies m in Model.MoviesList.Where(i => i.APIReferenceID == a.Id))
                        {
                            <p class="card-text">
                                <a class="btn btn-outline-dark" asp-area="" asp-controller="Movies" asp-action="MovieDetails" asp-route-slug="@m.Slug" asp-route-id="@m.SavedMoviesID">Movie Details</a>
                                <a class="btn btn-outline-warning d-none" asp-controller="Movies" asp-action="Edit" asp-route-id="@m.SavedMoviesID">Edit Movie</a>
                            </p>
                        }
                    </div>
                </div>
            }
        </div>
    </div>

</div>